"""Domain enumerations for VERIFY GH."""

from enum import StrEnum


class UserRole(StrEnum):
    CONSUMER = "CONSUMER"
    RETAILER = "RETAILER"
    REGULATOR = "REGULATOR"
    ADMIN = "ADMIN"


class VerificationStatus(StrEnum):
    MATCH = "MATCH"
    PARTIAL_MATCH = "PARTIAL_MATCH"
    DOES_NOT_MATCH = "DOES_NOT_MATCH"
    NOT_FOUND = "NOT_FOUND"
    VERIFICATION_UNAVAILABLE = "VERIFICATION_UNAVAILABLE"


class ReportStatus(StrEnum):
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    NEEDS_MORE_INFORMATION = "NEEDS_MORE_INFORMATION"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class ReportIssueType(StrEnum):
    REGISTRATION_DIFFERS = "REGISTRATION_DIFFERS"
    MANUFACTURER_DIFFERS = "MANUFACTURER_DIFFERS"
    PRODUCT_NAME_DIFFERS = "PRODUCT_NAME_DIFFERS"
    MISSING_REGISTRY_RECORD = "MISSING_REGISTRY_RECORD"
    PACKAGING_CONCERN = "PACKAGING_CONCERN"
    EXPIRED_OUTDATED = "EXPIRED_OUTDATED"
    OTHER = "OTHER"
